#!/usr/bin/env node
/**
 * One-command local development against a real Supabase stack.
 *
 *   npm run dev:local
 *
 * Steps (cross-platform):
 *   1. Verify Docker is running.
 *   2. `supabase start` — boots Postgres + Auth + Storage + Studio and applies
 *      supabase/migrations + seed.sql (per supabase/config.toml).
 *   3. Read the local credentials (`supabase status -o env`) and write them into
 *      .env.local with NEXT_PUBLIC_DEMO_MODE=false (merging, not clobbering).
 *   4. `next dev --webpack`.
 *
 * Stop the stack later with: npm run db:stop
 */
import { spawnSync, spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = join(root, ".env.local");
const isWin = process.platform === "win32";

// Ensure the locally-installed `supabase` CLI resolves whether this runs via
// `npm run dev:local` or `node scripts/dev-local.mjs` directly.
process.env.PATH = `${join(root, "node_modules", ".bin")}${isWin ? ";" : ":"}${process.env.PATH ?? ""}`;

const c = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
};
const step = (n, msg) => console.log(`\n${c.cyan(`[${n}/4]`)} ${c.bold(msg)}`);
const fail = (msg) => {
  console.error(`\n${c.red("✗")} ${msg}\n`);
  process.exit(1);
};

/** Run a command inheriting stdio; returns exit status. */
function run(cmd, args) {
  return spawnSync(cmd, args, { cwd: root, stdio: "inherit", shell: isWin }).status ?? 1;
}
/** Run a command capturing stdout (trimmed). Returns null on failure. */
function capture(cmd, args) {
  const r = spawnSync(cmd, args, { cwd: root, encoding: "utf8", shell: isWin });
  if (r.status !== 0) return null;
  return (r.stdout ?? "").trim();
}

// ── 1. Docker ────────────────────────────────────────────────────────────────
step(1, "Checking Docker…");
if (capture("docker", ["info", "--format", "{{.ServerVersion}}"]) === null) {
  fail(
    "Docker doesn't appear to be running.\n" +
      "  Install Docker Desktop and start it, then re-run " +
      c.cyan("npm run dev:local") +
      ".",
  );
}
console.log(c.green("✓ Docker is running"));

// ── 2. supabase start ────────────────────────────────────────────────────────
step(2, "Starting Supabase (this can take a minute on first run)…");
if (capture("supabase", ["--version"]) === null) {
  fail("The Supabase CLI isn't available. Run `npm install` (it's a devDependency).");
}
// `supabase start` is idempotent — if already running it just prints status.
if (run("supabase", ["start"]) !== 0) {
  fail("`supabase start` failed. See the output above (is another stack on these ports?).");
}

// ── 3. Write .env.local ──────────────────────────────────────────────────────
step(3, "Writing local credentials to .env.local…");
const statusEnv = capture("supabase", ["status", "-o", "env"]);
if (!statusEnv) fail("Couldn't read `supabase status`.");

const status = Object.fromEntries(
  statusEnv
    .split(/\r?\n/)
    .map((l) => l.match(/^([A-Z0-9_]+)="?(.*?)"?$/))
    .filter(Boolean)
    .map((m) => [m[1], m[2]]),
);

const managed = {
  NEXT_PUBLIC_DEMO_MODE: "false",
  NEXT_PUBLIC_APP_URL: "http://localhost:3000",
  NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: status.ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
  SUPABASE_STORAGE_BUCKET: "client-documents",
  DOCUMENT_SIGNED_URL_TTL: "120",
  EMAIL_PROVIDER: "console",
};
for (const [k, v] of Object.entries(managed)) {
  if (!v) fail(`supabase status did not return a value for ${k}.`);
}

let env = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "# Generated by npm run dev:local\n";
for (const [key, value] of Object.entries(managed)) {
  const line = `${key}=${value}`;
  const re = new RegExp(`^${key}=.*$`, "m");
  env = re.test(env) ? env.replace(re, line) : env.replace(/\n*$/, "\n") + line + "\n";
}
writeFileSync(ENV_PATH, env);
console.log(c.green("✓ .env.local updated") + c.dim(`  (Studio: ${status.STUDIO_URL}  ·  Mail: ${status.INBUCKET_URL ?? "http://localhost:54324"})`));

// ── 4. next dev ──────────────────────────────────────────────────────────────
step(4, "Launching the app (next dev --webpack)…");
console.log(c.dim("  Stop the database later with: npm run db:stop\n"));
const dev = spawn("next", ["dev", "--webpack"], { cwd: root, stdio: "inherit", shell: isWin });
dev.on("exit", (code) => process.exit(code ?? 0));
for (const sig of ["SIGINT", "SIGTERM"]) process.on(sig, () => dev.kill(sig));
